import { describe, expect, it } from "vitest";
import { markdownToText, renderMarkdown } from "../../site/admin/markdown-core.js";
import generatedSource from "../../site/admin/markdown-core.js?raw";

// The renderer's source of truth is a sibling checkout that CI does not have.
// A glob (unlike a static ?raw import) resolves to nothing instead of failing
// the whole file, and node:fs is unavailable inside the workers pool.
const siblingSources = import.meta.glob(
  "../../../../luci-app-aurora-config/.dev/src/resource/utils/markdown.js",
  { query: "?raw", import: "default", eager: true }
);
const appSource = Object.values(siblingSources)[0];

const OPEN_MARKER = "// <markdown-core>";
const CLOSE_MARKER = "// </markdown-core>";

function coreOf(source) {
  const start = source.indexOf(OPEN_MARKER);
  const end = source.indexOf(CLOSE_MARKER);
  return start === -1 || end === -1 ? null : source.slice(start, end + CLOSE_MARKER.length);
}

describe("site/admin/markdown-core.js is the app's markdown core, verbatim", () => {
  it.skipIf(!appSource)("matches the block between the markers in luci-app-aurora-config", () => {
    const appCore = coreOf(appSource);
    expect(appCore, "the app's markdown.js lost its <markdown-core> markers").not.toBeNull();
    if (coreOf(generatedSource) !== appCore) {
      expect.fail(
        "site/admin/markdown-core.js has drifted from luci-app-aurora-config's utils/markdown.js. " +
          "The console preview would no longer show what routers render. " +
          "Run `node scripts/sync-markdown.mjs` to resync."
      );
    }
  });

  it("is a generated module that carries a real core", () => {
    expect(generatedSource.startsWith("// Generated by scripts/sync-markdown.mjs")).toBe(true);
    expect(coreOf(generatedSource).length).toBeGreaterThan(1000);
    expect(generatedSource).not.toContain("innerHTML");
  });
});

// Just enough of a Document for the renderer, which only ever calls these.
function fakeDocument() {
  const node = (name) => ({
    name,
    attrs: {},
    children: [],
    appendChild(child) {
      this.children.push(child);
      return child;
    },
    setAttribute(key, value) {
      this.attrs[key] = value;
    },
  });
  return {
    createDocumentFragment: () => node("#fragment"),
    createElement: (tag) => node(tag),
    createTextNode: (text) => ({ name: "#text", text }),
  };
}

function outline(node) {
  if (node.name === "#text") return node.text;
  const href = node.attrs.href ? ` href=${node.attrs.href}` : "";
  return `<${node.name}${href}>${node.children.map(outline).join("")}</${node.name}>`;
}

describe("the synced core", () => {
  const httpsOnly = (url) => (url.startsWith("https://") ? url : "");

  it("builds elements for the subset and keeps HTML as text", () => {
    const tree = renderMarkdown(
      "**bold** and `code` <img src=x onerror=alert(1)>\n\n- one\n- two\n\n> quoted",
      fakeDocument(),
      httpsOnly
    );
    expect(outline(tree)).toBe(
      "<#fragment><p><strong>bold</strong> and <code>code</code> <img src=x onerror=alert(1)></p>" +
        "<ul><li>one</li><li>two</li></ul><blockquote>quoted</blockquote></#fragment>"
    );
    expect(tree.children[0].children.at(-1)).toEqual({ name: "#text", text: " <img src=x onerror=alert(1)>" });
  });

  it("links only what safeUrl lets through", () => {
    const tree = renderMarkdown("[ok](https://example.com/a) [bad](javascript:alert(1))", fakeDocument(), httpsOnly);
    const paragraph = tree.children[0];
    expect(paragraph.children.filter((child) => child.name === "a")).toHaveLength(1);
    expect(paragraph.children[0].attrs.href).toBe("https://example.com/a");
    expect(outline(paragraph)).not.toContain("href=javascript");
  });

  it("reduces a body to its first line of plain text", () => {
    expect(markdownToText("## **Heads up**\n\nbody")).toBe("Heads up");
  });
});
